version: '3'
services:
    db:
        image: mysql:5.7
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: msk
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
